In [ ]:
#Bài 1
a=int(input("Nhập a:"))
b=int(input("Nhập b:"))
print("Tổng là: ",a+b)
print("Hiệu là: ",a-b)
print("Tích là: ",a*b)
print("Thương là: ",float(a/b))

Nhập a:3
Nhập b:2
Tổng là:  5
Hiệu là:  1
Tích là:  6
Thương là:  1.5


In [ ]:
#Bài 2
chuoi="Hello World"
print(chuoi[2:5])

llo


In [ ]:
#Bài 4
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
if a>b:
  print("Hello World!")


Nhập a: 3
Nhập b: 2
Hello World!


In [ ]:
#Bài 5
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
if a==b:
  print("Yes")
else:
  print("No")


Nhập a: 2
Nhập b: 2
Yes


In [ ]:
#Bài 6
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
if a==b:
  print(1)
elif a>b:
  print(2)
else:
  print(3)

Nhập a: 3
Nhập b: 1
2


In [ ]:
#Bài 7
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
d=int(input("Nhập d: "))
if a==b & b==d:
  print("Hello World!")


Nhập a: 2
Nhập b: 2
Nhập d: 2
Hello World!


In [ ]:
#Bài 8
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
c=int(input("Nhập c: "))
d=int(input("Nhập d: "))
if a==b & c==d:
  print("Hello World!")

Nhập a: 2
Nhập b: 2
Nhập c: 2
Nhập d: 2
Hello World!


In [ ]:
#Bài 9
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
print("Yes") if a>b else print("No")

Nhập a: 3
Nhập b: 1
Yes


In [ ]:
#Bài 10
a=int(input("Nhập a: "))
b=int(input("Nhập b: "))
print("A") if a > b else print("=") if a == b else print("B")

Nhập a: 2
Nhập b: 3
B


In [ ]:
#Bài 11
a=list(range(0,10))
b=[]
for i in a:
  if i%2==0:
    b.append(i)
print(b)


[0, 2, 4, 6, 8]


In [ ]:
#Bài 12
a=list(range(0,1000))
tong=0
for i in a:
  if (i%3==0 or i%5==0):
    tong=tong+i
print(tong)

233168


In [ ]:
#Bài 13
a = [2, 3, 5, 7, 8]
b = [7, 3, 8, 9, 2, 10, 11]
c = []

ptmin = min(len(a), len(b))
for i in range(0, ptmin):
  c.append(a[i] + b[i])

if(len(a) > ptmin or len(b) > ptmin):
  for i in range(ptmin, len(a)):
    c.append(a[i])
  for i in range(ptmin, len(b)):
    c.append(b[i])

print(c)

[9, 6, 13, 16, 10, 10, 11]


In [ ]:
#Bài 14
import numpy as np
m=int(input("Nhập m: "))
n=int(input("Nhập n: "))

#a
print('a.')
arr = np.random.randint(0, 100, size=(m, n))
print("Mảng:\n", arr)

#b
print('\nb.')
k=int(input(f"Nhập dong muon xuat k(0->{m-1}): "))
# print(f"Dòng {k}:", arr[k,:])

#c
print('\nc.')
l=int(input(f"Nhập cot muon xuat l(0->{n-1}): "))
print(f"Cột {l}:", arr[:,l])

#d
print('\nd.')
print(f"Tổng các phần tử trên dòng {k}:", np.sum(arr[k, :]))

#e
print('\ne.')
print(f"Tích các phần tử trên cột {l}:", np.prod(arr[:, l]))

#f
print('\nf.')
for i in range(m):
  for j in range(n):
    if i%2==0 and j%2!=0:
      print(f"[{i},{j}]: {arr[i,j]}")

#g
print('\ng.')
count=0
tong=0
for i in range(m):
    if i % 2 != 0:
        for j in range(n):
            if arr[i, j] % 2 == 0:
              count=count+1
              tong=tong+arr[i,j]
if count==0:
  print("Không có phần tử chẵn")
else:
  print(f"Trung bình cộng các phần tử chẵn thuộc dòng lẻ: {tong / count:.2f}")

#h
print('\nh.')
tong = 0
count = 0
for i in range(m):
    for j in range(n):
        if i == 0 or i == m-1 or j == 0 or j == n-1:
            tong =tong+ arr[i, j]
            count = count + 1
print(f"Trung bình cộng phần tử biên: {tong / count:.2f}")

#i
print('\ni. ')
tong = 0
count = 0
for i in range(m):
    for j in range(n):
        if i != 0 and i != m-1 and j != 0 and j != n-1:
            tong =tong+ arr[i, j]
            count = count + 1
print(f"Trung bình cộng phần tử khôn44g thuộc biên: {tong / count:.2f}")

Nhập m: 4
Nhập n: 3
a.
Mảng:
 [[38 60 14]
 [ 2 76 31]
 [33 68 94]
 [ 4 97 74]]

b.
Nhập dong muon xuat k(0->3): 2

c.
Nhập cot muon xuat l(0->2): 1
Cột 1: [60 76 68 97]

d.
Tổng các phần tử trên dòng 2: 195

e.
Tích các phần tử trên cột 1: 30077760

f.
[0,1]: 60
[2,1]: 68

g.
Trung bình cộng các phần tử chẵn thuộc dòng lẻ: 39.00

h.
Trung bình cộng phần tử biên: 44.70

i. 
Trung bình cộng phần tử khôn44g thuộc biên: 72.00


In [ ]:
#Bài 15
class SinhVien:
  def __init__ (self, maSV, hoTen,namSinh, dtb):
    if len(maSV) != 10:
      raise ValueError("Mã sinh viên phải đúng 10 ký tự")
    if len(hoTen) > 20:
      raise ValueError("Tên tối đa 20 ký tự")
    if namSinh < 1900 or namSinh > 2026:
      raise ValueError("Năm sinh không hợp lệ")
    if dtb < 0 or dtb > 10:
      raise ValueError("Điểm phải từ 0 đến 10")
    self.maSV=maSV
    self.hoTen=hoTen
    self.namSinh=namSinh
    self.dtb=dtb

#Hàm xuất 1 sv
def XuatSinhVien(sv):
    print(sv.maSV, sv.hoTen, sv.namSinh, sv.dtb)
print("")


#Hàm xuất danh sách
def XuatDanhSach(ds):
    print("\nDanh sách sinh viên:")
    for sv in ds:
      print(sv.maSV, sv.hoTen, sv.namSinh, sv.dtb)
    print("")

#b
print('\nb.')
n = int(input("Nhập số sinh viên: "))
ds = []
for i in range(n):
    print(f"\nSinh viên {i+1}:")
    maSV = input("Mã SV: ")
    hoTen = input("Tên: ")
    namSinh = int(input("Năm sinh: "))
    dtb = float(input("Điểm TB: "))
    sv = SinhVien(maSV, hoTen, namSinh, dtb)
    ds.append(sv)
XuatDanhSach(ds)

#c
print('\nc.')
def DemSinhVienTheoDiemTB(ds):
    count=0
    for(sv) in ds:
      if sv.dtb >= 5:
        count=count+1
    return count
print(f"Số sinh viên có điểm TB >= 5: {DemSinhVienTheoDiemTB(ds)}")

#d
print('\nd.')
def SinhVienDu20Tuoi(ds):
    namht=2026
    for sv in ds:
      if namht-sv.namSinh >= 20:
        XuatSinhVien(sv)
print("Sinh viên có trên 20 tuổi:")
SinhVienDu20Tuoi(ds)

#e
print("\ne.")
def DemDH(ds):
    count = 0
    for sv in ds:
        if sv.maSV[2:4] == "DH":
            count += 1
    return count
print("Số SV hệ DH:", DemDH(ds))

#f
print("\nf.")
def DemTenLan(ds):
    count = 0
    for sv in ds:
        ten = sv.hoTen.split()[-1]
        if ten == "Lan":
            count += 1
    return count
print("Số SV tên Lan:", DemTenLan(ds))

#g
print("\ng.")
def DemHoPhan(ds):
    count = 0
    for sv in ds:
        ho = sv.hoTen.split()[0]
        if ho == "Phan":
            count += 1
    return count
print("Số SV họ Phan:", DemHoPhan(ds))

print("\nDanh sách test chức năng")
#test cụ thể
test = [
    SinhVien("01DH000001", "Phan Thi Lan", 2008, 7.5),
    SinhVien("02DH000002", "Nguyen Van An", 2003, 4.0),
    SinhVien("03CD000003", "Phan Van Binh", 2000, 6.5),
    SinhVien("04DH000004", "Le Thi Lan", 2005, 8.0),
    SinhVien("05CD000005", "Tran Minh Khoa", 1999, 5.0)
]
XuatDanhSach(test)
print(f"Số sinh viên có điểm TB >= 5: {DemSinhVienTheoDiemTB(test)}")
print("Sinh viên có trên 20 tuổi:")
SinhVienDu20Tuoi(test)
print("Số SV hệ DH:", DemDH(test))
print("Số SV tên Lan:", DemTenLan(test))
print("Số SV họ Phan:", DemHoPhan(test))



b.
Nhập số sinh viên: 2

Sinh viên 1:
Mã SV: 01DH000001
Tên: Phan Thi Lan
Năm sinh: 2008
Điểm TB: 7.5

Sinh viên 2:
Mã SV: 02DH000002
Tên: Nguyen Van An
Năm sinh: 2003
Điểm TB: 4.0

Danh sách sinh viên:
01DH000001 Phan Thi Lan 2008 7.5
02DH000002 Nguyen Van An 2003 4.0


c.
Số sinh viên có điểm TB >= 5: 1

d.
Sinh viên có trên 20 tuổi:
02DH000002 Nguyen Van An 2003 4.0

e.
Số SV hệ DH: 2

f.
Số SV tên Lan: 1

g.
Số SV họ Phan: 1

Danh sách test chức năng

Danh sách sinh viên:
01DH000001 Phan Thi Lan 2008 7.5
02DH000002 Nguyen Van An 2003 4.0
03CD000003 Phan Van Binh 2000 6.5
04DH000004 Le Thi Lan 2005 8.0
05CD000005 Tran Minh Khoa 1999 5.0

Số sinh viên có điểm TB >= 5: 4
Sinh viên có trên 20 tuổi:
02DH000002 Nguyen Van An 2003 4.0
03CD000003 Phan Van Binh 2000 6.5
04DH000004 Le Thi Lan 2005 8.0
05CD000005 Tran Minh Khoa 1999 5.0
Số SV hệ DH: 3
Số SV tên Lan: 2
Số SV họ Phan: 2
