In [ ]:
#Bài 1
a=[1,2,3,4,5]
b=[6,7,8,9,10,3,5,2]
def tron_mang(a, b):
    c = []
    n = min(len(a), len(b))
    for i in range(n):
        if a[i] < b[i]:
            c.append(a[i])
        else:
            c.append(b[i])
    if len(a) > len(b):
        c.extend(a[n:])
    else:
        c.extend(b[n:])
    return c
print(tron_mang(a, b))

[1, 2, 3, 4, 5, 3, 5, 2]


In [ ]:
#Bài 2
#a
import numpy as np
a=int(input("Nhập cấp a cho ma trận vuông : "))
arr = np.random.randint(0, 100, size=(a, a))
print("Mảng:\n", arr)

print("a.")
def TongTamGiacTren(a, n):
    tong = 0
    for i in range(n):
        for j in range(n):
            if i + j <= n - 1:
                tong += a[i][j]
    return tong

print(f"Tổng các phẩn tử của tam giác trên: {TongTamGiacTren(arr,a)}")

#b
n=int(input("Nhập dòng m: "))
m=int(input("Nhập cột n: "))
arr1 = np.random.randint(-100, 100, size=(m, n))
print("Mảng:\n", arr1)

print("\nb.")
def DoiAmThanhDuong(a, m, n):
    for i in range(m):
        for j in range(n):
            if a[i][j] < 0:
                a[i][j] = abs(a[i][j])
    return a
print(f"Sau khi dổi các phần tử âm thành dương trong ma trận:\n",DoiAmThanhDuong(arr1,m,n))

#c
print("\nc.")
def ThayChan(a,m,n,x):
  for i in range(m):
    for j in range(n):
      if a[i][j] %2==0:
        a[i][j]=x
  return a
x = int(input("Nhập số x: "))
print(f"Sau khi đổi các phần tử chẵn thành {x}:\n",ThayChan(arr1,m,n,x))

#d
print("\nd.")
def KTToanChan(a, m, n):
    for i in range(m):
        for j in range(n):
            if a[i][j] % 2 != 0:
                return False
    return True
print(f"Kiểm tra ma trận toàn chẵn: {KTToanChan(arr1,m,n)}")

#e
print("\ne.")
def KTDoiXung(a, n):
    for i in range(n):
        for j in range(n):
            if a[i][j] != a[j][i]:
                return False
    return True
print(f"Kiểm tra ma trận đối xứng: {KTDoiXung(arr,a)}")

#f
print("\nf.")
def KTDuongCheoChinhTangDan(a, n):
    for i in range(n - 1):
        if a[i][i] > a[i+1][i+1]:
            return False
    return True
print(f"Kiểm tra đường chéo chính tăng dần: {KTDuongCheoChinhTangDan(arr,a)}")

#g
print("\ng.")
def XuatTamGiacDuoiCheoPhu(a, n):
    for i in range(n):
        for j in range(n):
            if i + j >= n - 1:
                print(a[i][j], end=" ")
        print()
print("Tam giác dưới ma trận chéo phụ:")
XuatTamGiacDuoiCheoPhu(arr, a)

#h
print("\nh.")
def KTDuongCheoPhuGiamDan(a, n):
    for i in range(n - 1):
        if a[i][n-1-i] <= a[i+1][n-2-i]:
            return False
    return True
print(f"Kiểm tra đường chéo phụ giảm dần: {KTDuongCheoPhuGiamDan(arr,a)}")

#Ma trận test chức năng(thay đổi dể test)
print("\nMa trận test chức năng")
test = [
    [2, 4, 6],
    [4, 6, 8],
    [6, 8, 10]
]
for row in test:
    print(row)
print(f"Tổng các phẩn tử của tam giác trên: {TongTamGiacTren(test,3)}")
print(f"Kiểm tra ma trận đối xứng: {KTDoiXung(test,3)}")
print(f"Kiểm tra đường chéo chính tăng dần: {KTDuongCheoChinhTangDan(test,3)}")
print("Tam giác dưới ma trận chéo phụ:")
XuatTamGiacDuoiCheoPhu(test, 3)
print(f"Kiểm tra đường chéo phụ giảm dần: {KTDuongCheoPhuGiamDan(test,3)}")



Nhập cấp a cho ma trận vuông : 3
Mảng:
 [[61 63 28]
 [ 9 53 76]
 [42 44 53]]
a.
Tổng các phẩn tử của tam giác trên: 256
Nhập dòng m: 4
Nhập cột n: 5
Mảng:
 [[ 18 -86  95  37]
 [-28  86  93  -9]
 [ 30 -38 -58  11]
 [  5  95 -15  32]
 [ 23  62  -3 -82]]

b.
Sau khi dổi các phần tử âm thành dương trong ma trận:
 [[18 86 95 37]
 [28 86 93  9]
 [30 38 58 11]
 [ 5 95 15 32]
 [23 62  3 82]]

c.
Nhập số x: 0
Sau khi đổi các phần tử chẵn thành 0:
 [[ 0  0 95 37]
 [ 0  0 93  9]
 [ 0  0  0 11]
 [ 5 95 15  0]
 [23  0  3  0]]

d.
Kiểm tra ma trận toàn chẵn: False

e.
Kiểm tra ma trận đối xứng: False

f.
Kiểm tra đường chéo chính tăng dần: False

g.
Tam giác dưới ma trận chéo phụ:
28 
53 76 
42 44 53 

h.
Kiểm tra đường chéo phụ giảm dần: False

Ma trận test chức năng
[2, 4, 6]
[4, 6, 8]
[6, 8, 10]
Tổng các phẩn tử của tam giác trên: 28
Kiểm tra ma trận đối xứng: True
Kiểm tra đường chéo chính tăng dần: True
Tam giác dưới ma trận chéo phụ:
6 
6 8 
6 8 10 
Kiểm tra đường chéo phụ giảm dần: False
